name: flutter_app_development
description: Flutter App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud: ^0.1.3
  awesome_dialog: ^1.1.3
  cupertino_icons: ^0.1.3

  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7

  screenshot: ^0.2.0
  fl_chart: ^0.12.0
  image_gallery_saver: ^1.6.7
  carousel_slider: ^2.3.1
  http: ^0.12.2
  flutter_gradient_colors: ^1.0.0
  permission_handler: ^5.0.1+1
  google_sign_in: ^4.1.1
  intl: ^0.16.1
  validators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  #   - images/

